"""Generate theme.yaml for MinimalDark35 (writes the file in this directory).

Re-run after tweaking palette/layout constants below.
"""
from pathlib import Path
from textwrap import dedent

# --- palette / fonts ------------------------------------------------------
ACCENT = "95, 179, 214"          # cool cyan — used for bars and values
ACCENT_DIM = "70, 130, 160"
TXT = "224, 226, 230"            # primary text
TXT_DIM = "140, 144, 153"        # secondary
WARN = "232, 165, 70"            # for temps when hot (we use static here)
BAR_BG = "32, 35, 42"
GRAPH_LINE = "95, 179, 214"
GRAPH_AXIS = "70, 75, 84"

FONT_BOLD = "jetbrains-mono/JetBrainsMono-Bold.ttf"
FONT_EBOLD = "jetbrains-mono/JetBrainsMono-ExtraBold.ttf"
FONT_REG = "jetbrains-mono/JetBrainsMono-Regular.ttf"

BG = "background.png"

# --- per-core grid coordinates -------------------------------------------
PC_X0 = 10
PC_Y0 = 72       # row 0 top
PC_Y1 = 84       # row 1 top
PC_W = 15
PC_H = 8
PC_DX = 19       # column stride


def percore_block() -> str:
    lines = ["  CUSTOM:", "    INTERVAL: 1"]
    for i in range(32):
        row = 0 if i < 16 else 1
        col = i if i < 16 else i - 16
        x = PC_X0 + col * PC_DX
        y = PC_Y0 if row == 0 else PC_Y1
        lines.append(f"    CpuCore{i:02d}:")
        lines.append(f"      GRAPH:")
        lines.append(f"        SHOW: True")
        lines.append(f"        X: {x}")
        lines.append(f"        Y: {y}")
        lines.append(f"        WIDTH: {PC_W}")
        lines.append(f"        HEIGHT: {PC_H}")
        lines.append(f"        MIN_VALUE: 0")
        lines.append(f"        MAX_VALUE: 100")
        lines.append(f"        BAR_COLOR: {ACCENT}")
        lines.append(f"        BAR_OUTLINE: False")
        lines.append(f"        BACKGROUND_COLOR: {BAR_BG}")
    return "\n".join(lines)


# --- main theme body ------------------------------------------------------
def text(*, x, y, font, size, color, anchor="lt", show_unit=True, indent=8):
    """Build an indented TEXT stanza. Avoids WIDTH (which fights anchor=rt: it makes
    DisplayText treat the right edge as X+WIDTH, pushing right-anchored text off-screen).
    `indent` is the column where keys should land; first line is positioned by the caller's
    interpolation site, subsequent lines are prefixed with `indent` spaces."""
    pad = " " * indent
    return dedent(f"""\
        SHOW: True
        SHOW_UNIT: {show_unit}
        X: {x}
        Y: {y}
        FONT: {font}
        FONT_SIZE: {size}
        FONT_COLOR: {color}
        BACKGROUND_IMAGE: {BG}
        ANCHOR: {anchor}""").replace("\n", "\n" + pad)


def bar(*, x, y, w, h, color=ACCENT, indent=8):
    pad = " " * indent
    return dedent(f"""\
        SHOW: True
        X: {x}
        Y: {y}
        WIDTH: {w}
        HEIGHT: {h}
        MIN_VALUE: 0
        MAX_VALUE: 100
        BAR_COLOR: {color}
        BAR_OUTLINE: False
        BACKGROUND_COLOR: {BAR_BG}""").replace("\n", "\n" + pad)


THEME = f"""---
# MinimalDark35 — clean dark portrait theme for 3.5" Turing-style displays.
# Generated by _gen_theme.py. Edit palette/layout constants there, not here.
author: "Ramb0t (with Claude)"

display:
  DISPLAY_ORIENTATION: portrait
  DISPLAY_SIZE: 3.5"
  DISPLAY_RGB_LED: 0, 0, 0

static_images:
  BACKGROUND:
    PATH: {BG}
    X: 0
    Y: 0
    WIDTH: 320
    HEIGHT: 480

STATS:
  DATE:
    INTERVAL: 1
    HOUR:
      TEXT:
        {text(x=10, y=6, font=FONT_EBOLD, size=16, color=TXT)}
    DAY:
      TEXT:
        {text(x=310, y=9, font=FONT_REG, size=11, color=TXT_DIM, anchor="rt")}

  CPU:
    PERCENTAGE:
      INTERVAL: 1
      TEXT:
        {text(x=310, y=98, font=FONT_BOLD, size=14, color=TXT, anchor="rt")}
      GRAPH:
        {bar(x=10, y=100, w=240, h=12)}
    FREQUENCY:
      INTERVAL: 2
      TEXT:
        {text(x=10, y=122, font=FONT_BOLD, size=18, color=ACCENT)}
    TEMPERATURE:
      INTERVAL: 2
      TEXT:
        {text(x=310, y=36, font=FONT_EBOLD, size=22, color=TXT, anchor="rt")}
    FAN_SPEED:
      INTERVAL: 5
      TEXT:
        {text(x=310, y=126, font=FONT_REG, size=11, color=TXT_DIM, anchor="rt")}

  GPU:
    INTERVAL: 1
    PERCENTAGE:
      TEXT:
        {text(x=310, y=213, font=FONT_BOLD, size=14, color=TXT, anchor="rt")}
      GRAPH:
        {bar(x=10, y=214, w=240, h=12)}
    MEMORY_PERCENT:
      GRAPH:
        {bar(x=10, y=234, w=240, h=8, color=ACCENT_DIM)}
    MEMORY_USED:
      TEXT:
        {text(x=310, y=232, font=FONT_REG, size=11, color=TXT_DIM, anchor="rt")}
    TEMPERATURE:
      TEXT:
        {text(x=310, y=176, font=FONT_EBOLD, size=22, color=TXT, anchor="rt")}

  MEMORY:
    INTERVAL: 5
    VIRTUAL:
      GRAPH:
        {bar(x=10, y=292, w=300, h=12)}
      PERCENT_TEXT:
        {text(x=310, y=264, font=FONT_BOLD, size=14, color=TXT, anchor="rt")}
      USED:
        {text(x=10, y=310, font=FONT_REG, size=11, color=TXT_DIM)}
      TOTAL:
        {text(x=310, y=310, font=FONT_REG, size=11, color=TXT_DIM, anchor="rt")}

  DISK:
    INTERVAL: 10
    USED:
      GRAPH:
        {bar(x=10, y=356, w=300, h=12)}
      PERCENT_TEXT:
        {text(x=310, y=328, font=FONT_BOLD, size=14, color=TXT, anchor="rt")}
      TEXT:
        {text(x=10, y=374, font=FONT_REG, size=11, color=TXT_DIM)}
    TOTAL:
      TEXT:
        {text(x=310, y=374, font=FONT_REG, size=11, color=TXT_DIM, anchor="rt")}

  NET:
    INTERVAL: 2
    ETH:
      DOWNLOAD:
        TEXT:
          {text(x=150, y=394, font=FONT_BOLD, size=11, color=ACCENT, anchor="rt", indent=10)}
        LINE_GRAPH:
          SHOW: True
          X: 10
          Y: 414
          WIDTH: 145
          HEIGHT: 56
          MIN_VALUE: 0
          MAX_VALUE: 1000000
          HISTORY_SIZE: 80
          AUTOSCALE: True
          LINE_COLOR: {GRAPH_LINE}
          LINE_WIDTH: 2
          AXIS: False
          BACKGROUND_IMAGE: {BG}
      UPLOAD:
        TEXT:
          {text(x=310, y=394, font=FONT_BOLD, size=11, color=ACCENT, anchor="rt", indent=10)}
        LINE_GRAPH:
          SHOW: True
          X: 165
          Y: 414
          WIDTH: 145
          HEIGHT: 56
          MIN_VALUE: 0
          MAX_VALUE: 1000000
          HISTORY_SIZE: 80
          AUTOSCALE: True
          LINE_COLOR: {ACCENT_DIM}
          LINE_WIDTH: 2
          AXIS: False
          BACKGROUND_IMAGE: {BG}

{percore_block()}
"""


def main():
    out = Path(__file__).with_name("theme.yaml")
    out.write_text(THEME)
    print(f"wrote {out}  ({len(THEME.splitlines())} lines)")


if __name__ == "__main__":
    main()
