"""Generate theme.yaml for MinimalDark88 (writes the file in this directory).

Re-run after tweaking palette/layout constants below.
"""
from pathlib import Path
from textwrap import dedent

# --- palette / fonts -------------------------------------------------------
ACCENT     = "95, 179, 214"    # cool cyan
ACCENT_DIM = "70, 130, 160"
TXT        = "224, 226, 230"
TXT_DIM    = "140, 144, 153"
BAR_BG     = "32, 35, 42"
GRAPH_LINE = "95, 179, 214"

FONT_BOLD  = "jetbrains-mono/JetBrainsMono-Bold.ttf"
FONT_EBOLD = "jetbrains-mono/JetBrainsMono-ExtraBold.ttf"
FONT_REG   = "jetbrains-mono/JetBrainsMono-Regular.ttf"

BG = "background.png"

# --- section Y-anchors (tweak here for spacing) ----------------------------
#   HEADER  0..80
#   CPU    80..580
#   GPU   580..1020
#   MEM  1020..1270
#   DISK 1270..1520
#   NET  1520..1920

# --- per-core grid ---------------------------------------------------------
PC_X0 = 12
PC_W  = 24
PC_H  = 26
PC_DX = 28    # 12 + 15*28 + 24 = 456  (24px right margin)


def percore_block() -> str:
    lines = ["  CUSTOM:", "    INTERVAL: 1"]
    for i in range(32):
        row = 0 if i < 16 else 1
        col = i if i < 16 else i - 16
        x = PC_X0 + col * PC_DX
        y = 280 if row == 0 else 316
        lines.append(f"    CpuCore{i:02d}:")
        lines.append(f"      GRAPH:")
        lines.append(f"        SHOW: True")
        lines.append(f"        X: {x}")
        lines.append(f"        Y: {y}")
        lines.append(f"        WIDTH: {PC_W}")
        lines.append(f"        HEIGHT: {PC_H}")
        lines.append(f"        MIN_VALUE: 0")
        lines.append(f"        MAX_VALUE: 100")
        lines.append(f"        BAR_COLOR: {ACCENT}")
        lines.append(f"        BAR_OUTLINE: False")
        lines.append(f"        BACKGROUND_COLOR: {BAR_BG}")
    return "\n".join(lines)


# --- helpers ---------------------------------------------------------------
def text(*, x, y, font, size, color, anchor="lt", show_unit=True, indent=8):
    pad = " " * indent
    return dedent(f"""\
        SHOW: True
        SHOW_UNIT: {show_unit}
        X: {x}
        Y: {y}
        FONT: {font}
        FONT_SIZE: {size}
        FONT_COLOR: {color}
        BACKGROUND_IMAGE: {BG}
        ANCHOR: {anchor}""").replace("\n", "\n" + pad)


def bar(*, x, y, w, h, color=ACCENT, indent=8):
    pad = " " * indent
    return dedent(f"""\
        SHOW: True
        X: {x}
        Y: {y}
        WIDTH: {w}
        HEIGHT: {h}
        MIN_VALUE: 0
        MAX_VALUE: 100
        BAR_COLOR: {color}
        BAR_OUTLINE: False
        BACKGROUND_COLOR: {BAR_BG}""").replace("\n", "\n" + pad)


def linegraph(*, x, y, w, h, min_v=0, max_v=100, autoscale=False,
              color=GRAPH_LINE, history=120, indent=8):
    pad = " " * indent
    return dedent(f"""\
        SHOW: True
        X: {x}
        Y: {y}
        WIDTH: {w}
        HEIGHT: {h}
        MIN_VALUE: {min_v}
        MAX_VALUE: {max_v}
        HISTORY_SIZE: {history}
        AUTOSCALE: {autoscale}
        LINE_COLOR: {color}
        LINE_WIDTH: 2
        AXIS: False
        BACKGROUND_IMAGE: {BG}""").replace("\n", "\n" + pad)


# --- theme body ------------------------------------------------------------
THEME = f"""---
# MinimalDark88 — clean dark portrait theme for 8.8" Turing displays (480×1920).
# Generated by _gen_theme.py. Edit constants there, not here.
author: "Ramb0t (with Claude)"

display:
  DISPLAY_ORIENTATION: portrait
  DISPLAY_SIZE: 8.8"
  DISPLAY_RGB_LED: 0, 0, 0

static_images:
  BACKGROUND:
    PATH: {BG}
    X: 0
    Y: 0
    WIDTH: 480
    HEIGHT: 1920

STATS:
  # ── HEADER ───────────────────────────────────────────────────────────────
  DATE:
    INTERVAL: 1
    HOUR:
      TEXT:
        {text(x=20, y=8, font=FONT_EBOLD, size=60, color=TXT)}
    DAY:
      TEXT:
        {text(x=460, y=10, font=FONT_REG, size=22, color=TXT_DIM, anchor="rt")}
    DATE:
      TEXT:
        {text(x=460, y=42, font=FONT_REG, size=18, color=TXT_DIM, anchor="rt")}

  # ── CPU ──────────────────────────────────────────────────────────────────
  CPU:
    PERCENTAGE:
      INTERVAL: 1
      TEXT:
        {text(x=460, y=130, font=FONT_BOLD, size=44, color=TXT, anchor="rt")}
      GRAPH:
        {bar(x=20, y=245, w=440, h=22)}
      LINE_GRAPH:
        {linegraph(x=20, y=358, w=440, h=130, autoscale=False)}
    TEMPERATURE:
      INTERVAL: 1
      TEXT:
        {text(x=20, y=125, font=FONT_EBOLD, size=58, color=TXT)}
    FREQUENCY:
      INTERVAL: 2
      TEXT:
        {text(x=20, y=200, font=FONT_BOLD, size=28, color=ACCENT)}
    FAN_SPEED:
      INTERVAL: 5
      TEXT:
        {text(x=460, y=205, font=FONT_REG, size=20, color=TXT_DIM, anchor="rt")}

  # ── GPU ──────────────────────────────────────────────────────────────────
  # GPU card yt=582, HDR_H=36 → divider at 618; content starts at 626+
  GPU:
    INTERVAL: 1
    PERCENTAGE:
      TEXT:
        {text(x=460, y=630, font=FONT_BOLD, size=44, color=TXT, anchor="rt")}
      GRAPH:
        {bar(x=20, y=745, w=440, h=22)}
      LINE_GRAPH:
        {linegraph(x=20, y=832, w=440, h=130, autoscale=False)}
    TEMPERATURE:
      TEXT:
        {text(x=20, y=625, font=FONT_EBOLD, size=58, color=TXT)}
    MEMORY_PERCENT:
      GRAPH:
        {bar(x=20, y=775, w=440, h=14, color=ACCENT_DIM)}
    MEMORY_USED:
      TEXT:
        {text(x=20, y=697, font=FONT_REG, size=22, color=TXT_DIM)}
    MEMORY_TOTAL:
      TEXT:
        {text(x=460, y=697, font=FONT_REG, size=22, color=TXT_DIM, anchor="rt")}

  # ── MEMORY ───────────────────────────────────────────────────────────────
  # MEM card yt=1022, HDR_H=36 → divider at 1058; content starts at 1063+
  MEMORY:
    INTERVAL: 5
    VIRTUAL:
      PERCENT_TEXT:
        {text(x=460, y=1063, font=FONT_BOLD, size=44, color=TXT, anchor="rt")}
      GRAPH:
        {bar(x=20, y=1123, w=440, h=22)}
      USED:
        {text(x=20, y=1156, font=FONT_REG, size=20, color=TXT_DIM)}
      TOTAL:
        {text(x=460, y=1156, font=FONT_REG, size=20, color=TXT_DIM, anchor="rt")}

  # ── DISK ─────────────────────────────────────────────────────────────────
  # DISK card yt=1272, HDR_H=36 → divider at 1308; content starts at 1313+
  DISK:
    INTERVAL: 10
    USED:
      PERCENT_TEXT:
        {text(x=460, y=1313, font=FONT_BOLD, size=44, color=TXT, anchor="rt")}
      GRAPH:
        {bar(x=20, y=1373, w=440, h=22)}
      TEXT:
        {text(x=20, y=1406, font=FONT_REG, size=20, color=TXT_DIM)}
    TOTAL:
      TEXT:
        {text(x=460, y=1406, font=FONT_REG, size=20, color=TXT_DIM, anchor="rt")}

  # ── NETWORK ──────────────────────────────────────────────────────────────
  # NET card yt=1522, HDR_H=36 → divider at 1558; content starts at 1562+
  NET:
    INTERVAL: 2
    ETH:
      DOWNLOAD:
        TEXT:
          {text(x=460, y=1562, font=FONT_BOLD, size=22, color=ACCENT, anchor="rt", indent=10)}
        LINE_GRAPH:
          SHOW: True
          X: 20
          Y: 1596
          WIDTH: 440
          HEIGHT: 140
          MIN_VALUE: 0
          MAX_VALUE: 1000000
          HISTORY_SIZE: 120
          AUTOSCALE: True
          LINE_COLOR: {GRAPH_LINE}
          LINE_WIDTH: 2
          AXIS: False
          BACKGROUND_IMAGE: {BG}
      UPLOAD:
        TEXT:
          {text(x=460, y=1748, font=FONT_BOLD, size=22, color=ACCENT, anchor="rt", indent=10)}
        LINE_GRAPH:
          SHOW: True
          X: 20
          Y: 1782
          WIDTH: 440
          HEIGHT: 130
          MIN_VALUE: 0
          MAX_VALUE: 1000000
          HISTORY_SIZE: 120
          AUTOSCALE: True
          LINE_COLOR: {ACCENT_DIM}
          LINE_WIDTH: 2
          AXIS: False
          BACKGROUND_IMAGE: {BG}

{percore_block()}
"""


def main():
    out = Path(__file__).with_name("theme.yaml")
    out.write_text(THEME)
    print(f"wrote {out}  ({len(THEME.splitlines())} lines)")


if __name__ == "__main__":
    main()
